### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by soda723** [psyStudy/CS_study#13]
- 별도의 메모리 공간에 물리공간어디?
- 컬럼 데이터 정렬 말 수정
- RDBMS 설명 추가 한줄
- 클러스터 인덱스 사용시 모든 보조 인덱스가 pk를 포함한다.
- 종류 내용 보충

**Comment by M1nseoPark** [comment]
RDBMS는 안해도 될 것 같아! 내가 할게
NoSQL 할 때 나오네

**Comment by soda723** [comment]
- 테이블 데이터와 다른 파일이라고 이해하면 될 것 같음
- 수정완료(컬럼 데이터를 정렬한 후 -> 컬럼을 기준으로 데이터를 정렬한 후)
- 패스

**Comment by soda723** [comment]
- 인덱스의 종류 페이지 분리해서 업데이트
