### ISSUE TITLE
캐시

### ISSUE THREAD

**Issue by M1nseoPark** [psyStudy/CS_study#4]
쓰기 정책 실제 사용 예시

**Comment by soda723** [comment]
A) 서비스 특성에 따라 캐시 정책을 다르게 설정함.  /  write-through 사용 서비스 예시로 AWS DAX 언급 추가 / 캐시 구현 예제 참고 링크 추가(Google Guava Cache)

**Comment by soda723** [comment]
답변완료

**Comment by soda723** [comment]
레지스터 : 순서바꾸기 
SDRAM 정확하게 어디 사용하는지
메모를 안해둠 > 둘 다 답변완료
