### ISSUE TITLE
클래스/객체/인스턴스, static과 non-static, 원시타입/참조타입

### ISSUE THREAD

**Issue by soda723** [psyStudy/CS_study#44]
- JVM메모리의 클래스 영역에 로드 ????
- static JVM 어디 저장되는 
- static 변수 초기화 해줘야
- 인스턴스 변수와 지역변수 차이??
- 왜 스태틱 메소들 클래스만 있는 상태에서 호출하는 것을 지양해야하는

**Comment by soda723** [comment]
1.
- jvm에서 메소드 영역=static영역=class 영역 이라고도 함.(클래스 로더는 아님)
- 따라서 클래스가 생성되면 그 클래스에 대한 정보, static 변수 등등이 메소드 영역에 저장, 로드 됨.
2.
- static 변수도 jvm의 메소드영역=static영역=class영역에 저장된다.

**Comment by soda723** [comment]
4. 인스턴스 변수와 지역변수 차이??
i) 일단 선언 위치에 따라 전역변수와 지역변수로 나눌 수 있다.
ii) 전역 변수를 다시 클래스(static)변수와 인스턴스 변수로 구분할 수 있다.

자세한 내용 페이지 참고!

**Comment by soda723** [comment]
3. static 변수 초기화 해줘야...
만약 전역변수(클래스변수, 인스턴스 변수)를 초기화 안해도 자료형에 맞게 알아서 초기화 해주기는 한다.

**Comment by soda723** [comment]
5. 왜 스태틱 메소들 클래스만 있는 상태에서 호출하는 것을 지양해야하는지
 -> 완전 잘못된 내용. 수정함.
-> static 메소드를 '인스턴스'생성 후에도 사용하는 것을 지양
- 인스턴스 생성 후에도 사용하는 메소드라면 static을 사용하지 않는 것이 바람직하다. (객체지향적 관점)
- 페이지에 자세하게 설명 추가

**Comment by soda723** [comment]
Q 지역 변수 예시 다시

**Comment by soda723** [comment]
참조타입에서 boxing/unboxing 내용 삭제 (래퍼 클래스 내용 확인)

**Comment by soda723** [comment]
지역변수 = 메소드, 생성자, 초기화 블록 내부 변수로 수정
박싱,언박싱 삭제

**Comment by M1nseoPark** [comment]
- 클래스 변수 부분에서 "처음 JVM이 실행되어 클래스가 메모리에 올라갈 때 ~ 프로그램이 종료될 때까지 유지(메소드 영역=클래스 영역=static 영역에 저장된다.)", "객체를 생성하지 않고 static 자원에 접근가능 (stack 메모리 영역에 존재하므로)" 둘이 말이 안맞음...
찾아보니까 메소드 영역에 저장되는 게 맞는듯 (stack 영역 아님)

- "제너릭 타입에서 사용할 수 없다. ## 다시조사" -> 조사 안되어 있음
