### ISSUE TITLE
형 변환 Promotion, Casting

### ISSUE THREAD

**Issue by soda723** [psyStudy/CS_study#57]
- Domain 정의 정확하게
- int float, 메모리 크기 있는 원시타입 페이지 링크 추가
- 자바는 String+ int 오류가 안나나요?
-

**Comment by soda723** [comment]
- 도메인이 해당 맥략에서는 오히려 정확하지 않은 것 같아서 '자료형이 표현 할 수 있는 숫자의 범위'로 변경
- (뭔가 객체까지 포함하기 위한 의미로 쓰기 위한 느낌?)
- 도메인 : (넓은 의미에서) 해결하고자 하는 문제의 영역

**Comment by soda723** [comment]
링크추가

**Comment by soda723** [comment]
자바는 String+ int 오류가 안나나요? 안난다!
(페이지에 예시 코드랑 실행 결과 첨부)

**Comment by M1nseoPark** [comment]
프로모션 = 업캐스팅 = 자동형변환이 맞다 
어차피 부모-자식 관계도 자식(더 작은 유형)이 부모(더 큰 유형)으로 형변환 되는 것이기 때문에 클래스 관계에서도 원리가 같음 
https://www.javainterviewpoint.com/type-casting-java-implicit-explicit-casting/

거의 프로모션이라는 용어는 쓰이지 않고 업캐스팅이라고 한대
https://okky.kr/questions/642926
