### ISSUE TITLE
가상 메모리 

### ISSUE THREAD

**Issue by M1nseoPark** [psyStudy/CS_study#6]
1. mmu vs 메모리맵 
2. trap 설명 추가 
3. 스레싱

**Comment by soda723** [comment]
가상메모리 장점에서 더 많은 프로그램을 동시에 순차적으로 실행한다는 말이 뭐야? 동시실행=실제로는 빠르게 돌아가면서 순차적으로라는 말인가

**Comment by M1nseoPark** [comment]
맞습니다 소다님

**Comment by M1nseoPark** [comment]
메모리맵은 사진이 잘못 나온듯ㅠ 지금 펜슬이 없어서 집에 가서 사진 수정하겠음 
메모리맵 -> 페이지 테이블
